sudo: required
services:
  - docker
before_install:
  - docker build -t aditya/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true aditya/react-test npm test
after_success:
  - docker build -t adityaranjan65/multi-client ./client
  - docker build -t adityaranjan65/multi-nginx ./nginx
  - docker build -t adityaranjan65/multi-server ./server
  - docker build -t adityaranjan65/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adityaranjan65/multi-client
  - docker push adityaranjan65/multi-nginx
  - docker push adityaranjan65/multi-server
  - docker push adityaranjan65/multi-worker